"""
Frozen Stage12 confirmed rewire runtime.

Generated by Stage 12.11G3H3E2B from the exact
live functions that produced the locked Fold0
confirmation.

Policy:
    ASYM1x5_Q9990_NO_TARGET_CUT_V1

This module is engineering packaging only.
Scientific selection is closed.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
import hashlib
import json
import gc

import joblib
import numpy as np
import pandas as pd

from biohub_cell_tracking import frozen_v9 as fv9

from scipy.spatial._ckdtree import cKDTree


# ========================================================
# FROZEN POLICY CONTRACT
# ========================================================

POLICY_ID = 'ASYM1x5_Q9990_NO_TARGET_CUT_V1'
POLICY_SHA256 = '77f0b07cafb21d0705917ff71b750fde45f3c7ddc17c13fecaff0ac673ebf776'
DEPLOYMENT_THRESHOLD = 0.9952878577709198
MODEL_SHA256 = '00918fa386d4de6e6a5f93892e47d876e6ff45ceb89670f982ebba45f59ebf76'
PREPROCESSOR_SHA256 = '6b5425093efd17613c68fcba855a756a3445a286a61ac813a83652dd2200ae41'
FEATURE_SCHEMA_SHA256 = '0a9f8e9a41c5c80c803c3a95955702dcf4039605a21fc656a154aa05be55b39c'

EPS = 1e-12
MAX_GAP_SIZE = 12
MIN_GAP_SIZE = 2
QUERY_K = 16
RANK_SCORES = ['SYM_CV', 'MAX_CV', 'GMEAN_RATIO']
SCALE = np.array([1.625, 0.40625, 0.40625], dtype=np.dtype('float64'))

FEATURE_COLUMNS = ['gap_size', 'delta_t', 'source_occupied', 'target_occupied', 'cuts', 'source_cv_pf', 'target_cv_pf', 'MIN_CV', 'SYM_CV', 'MAX_CV', 'GMEAN_RATIO', 'GM_SOURCE_RANK', 'GM_TARGET_RANK', 'GM_BEST_RANK', 'GM_MAX_RANK', 'GM_RANK_SUM', 'GM_RANK_LOG_ASYMMETRY', 'SOURCE_COMPETITION_COUNT', 'TARGET_COMPETITION_COUNT', 'GM_SOURCE_RANK_FRAC', 'GM_TARGET_RANK_FRAC', 'GM_BEST_RANK_FRAC', 'SYM_BEST_RANK', 'MAX_BEST_RANK', 'source_incumbent_cv_pf', 'target_incumbent_cv_pf', 'source_relative_improvement', 'target_relative_improvement', 'max_required_improvement', 'min_required_improvement', 'mean_required_improvement', 'dominance_all']


# ========================================================
# EXACT NOTEBOOK-DERIVED FUNCTIONS
# ========================================================

def safe_ratio(
    candidate,
    best,
):

    candidate = float(
        candidate
    )

    best = float(
        best
    )


    if best <= EPS:

        if candidate <= EPS:

            return 1.0

        return np.inf


    return float(
        candidate
        /
        best
    )


def query_knn(
    query_points,
    candidate_points,
    k,
):

    query_points = np.asarray(
        query_points,
        dtype=float,
    )


    candidate_points = np.asarray(
        candidate_points,
        dtype=float,
    )


    if (
        len(
            query_points
        ) == 0
        or
        len(
            candidate_points
        ) == 0
    ):

        return (
            np.empty(
                (
                    len(
                        query_points
                    ),
                    0,
                ),
                dtype=float,
            ),

            np.empty(
                (
                    len(
                        query_points
                    ),
                    0,
                ),
                dtype=int,
            ),
        )


    k_eff = min(
        int(
            k
        ),
        int(
            len(
                candidate_points
            )
        ),
    )


    tree = cKDTree(
        candidate_points
    )


    distances, indices = tree.query(
        query_points,
        k=k_eff,
    )


    if k_eff == 1:

        distances = distances[
            :,
            None
        ]

        indices = indices[
            :,
            None
        ]


    return (
        np.asarray(
            distances,
            dtype=float,
        ),

        np.asarray(
            indices,
            dtype=int,
        ),
    )


def make_rank_map(
    query_ids,
    candidate_ids,
    distances,
    indices,
    reverse_pair=False,
):

    result = {}


    for query_i, query_id in enumerate(
        query_ids
    ):

        for rank_i in range(
            indices.shape[
                1
            ]
        ):

            candidate_id = int(
                candidate_ids[
                    indices[
                        query_i,
                        rank_i
                    ]
                ]
            )


            if reverse_pair:

                pair = (
                    candidate_id,
                    int(
                        query_id
                    ),
                )

            else:

                pair = (
                    int(
                        query_id
                    ),
                    candidate_id,
                )


            if pair not in result:

                result[
                    pair
                ] = (
                    int(
                        rank_i
                        +
                        1
                    ),

                    float(
                        distances[
                            query_i,
                            rank_i
                        ]
                    ),
                )


    return result


def asym_3x8(
    source_rank,
    target_rank,
):

    return bool(
        (
            source_rank <= 3
            and
            target_rank <= 8
        )
        or
        (
            target_rank <= 3
            and
            source_rank <= 8
        )
    )


def generate_dataset_proposals(
    dataset,
):

    graph, scale = build_current_best(
        dataset
    )


    scale = np.asarray(
        scale,
        dtype=float,
    )


    assert np.allclose(
        scale,
        SCALE,
        atol=1e-12,
        rtol=0.0,
    )


    # --------------------------------------------------------
    # Nodes
    # --------------------------------------------------------

    nodes = (
        graph.node_attrs(
            attr_keys=[
                "node_id",
                "t",
                "z",
                "y",
                "x",
            ]
        )
        .to_pandas()
        .copy()
    )


    nodes[
        "node_id"
    ] = nodes[
        "node_id"
    ].astype(
        int
    )


    nodes[
        "t"
    ] = nodes[
        "t"
    ].astype(
        int
    )


    nodes = (
        nodes
        .sort_values(
            [
                "t",
                "node_id",
            ],
            kind="stable",
        )
        .set_index(
            "node_id",
            drop=False,
        )
    )


    # --------------------------------------------------------
    # Edges
    # --------------------------------------------------------

    edges = (
        graph.edge_attrs(
            unpack=True
        )
        .to_pandas()
        .copy()
    )


    edges[
        "source_id"
    ] = edges[
        "source_id"
    ].astype(
        int
    )


    edges[
        "target_id"
    ] = edges[
        "target_id"
    ].astype(
        int
    )


    edge_set = set(
        zip(
            edges[
                "source_id"
            ],
            edges[
                "target_id"
            ],
        )
    )


    incoming = (
        edges.groupby(
            "target_id"
        )[
            "source_id"
        ]
        .apply(
            list
        )
        .to_dict()
    )


    outgoing = (
        edges.groupby(
            "source_id"
        )[
            "target_id"
        ]
        .apply(
            list
        )
        .to_dict()
    )


    indeg = (
        edges.groupby(
            "target_id"
        )
        .size()
        .astype(
            int
        )
        .to_dict()
    )


    outdeg = (
        edges.groupby(
            "source_id"
        )
        .size()
        .astype(
            int
        )
        .to_dict()
    )


    indeg = {
        int(k):
            int(v)

        for k, v
        in indeg.items()
    }


    outdeg = {
        int(k):
            int(v)

        for k, v
        in outdeg.items()
    }


    # --------------------------------------------------------
    # Physical state
    # --------------------------------------------------------

    phys = {}

    time_map = {}


    for nid, row in nodes.iterrows():

        nid = int(
            nid
        )


        phys[
            nid
        ] = (
            np.array(
                [
                    float(
                        row[
                            "z"
                        ]
                    ),
                    float(
                        row[
                            "y"
                        ]
                    ),
                    float(
                        row[
                            "x"
                        ]
                    ),
                ],
                dtype=float,
            )
            *
            SCALE
        )


        time_map[
            nid
        ] = int(
            row[
                "t"
            ]
        )


    node_ids = sorted(
        phys
    )


    # --------------------------------------------------------
    # Past / future velocities
    # --------------------------------------------------------

    past_velocity = {}

    future_velocity = {}


    for nid in node_ids:

        inc = incoming.get(
            nid,
            [],
        )


        if len(
            inc
        ) == 1:

            prev_id = int(
                inc[
                    0
                ]
            )


            if prev_id in phys:

                dt = (
                    time_map[
                        nid
                    ]
                    -
                    time_map[
                        prev_id
                    ]
                )


                if dt > 0:

                    past_velocity[
                        nid
                    ] = (
                        phys[
                            nid
                        ]
                        -
                        phys[
                            prev_id
                        ]
                    ) / float(
                        dt
                    )


        out = outgoing.get(
            nid,
            [],
        )


        if len(
            out
        ) == 1:

            next_id = int(
                out[
                    0
                ]
            )


            if next_id in phys:

                dt = (
                    time_map[
                        next_id
                    ]
                    -
                    time_map[
                        nid
                    ]
                )


                if dt > 0:

                    future_velocity[
                        nid
                    ] = (
                        phys[
                            next_id
                        ]
                        -
                        phys[
                            nid
                        ]
                    ) / float(
                        dt
                    )


    # --------------------------------------------------------
    # Eligible endpoints
    # --------------------------------------------------------

    source_eligible = [
        nid

        for nid
        in node_ids

        if (
            outdeg.get(
                nid,
                0,
            )
            <=
            1
            and
            nid in past_velocity
        )
    ]


    target_eligible = [
        nid

        for nid
        in node_ids

        if (
            indeg.get(
                nid,
                0,
            )
            <=
            1
            and
            nid in future_velocity
        )
    ]


    # --------------------------------------------------------
    # Incumbent normalized CV costs
    # --------------------------------------------------------

    source_incumbent = {}

    target_incumbent = {}


    for src in source_eligible:

        if outdeg.get(
            src,
            0,
        ) != 1:

            continue


        current_out = outgoing.get(
            src,
            [],
        )


        assert len(
            current_out
        ) == 1


        old_tgt = int(
            current_out[
                0
            ]
        )


        dt_old = (
            time_map[
                old_tgt
            ]
            -
            time_map[
                src
            ]
        )


        if dt_old <= 0:

            continue


        predicted_target = (
            phys[
                src
            ]
            +
            float(
                dt_old
            )
            *
            past_velocity[
                src
            ]
        )


        source_incumbent[
            src
        ] = (
            float(
                np.linalg.norm(
                    phys[
                        old_tgt
                    ]
                    -
                    predicted_target
                )
            )
            /
            float(
                dt_old
            )
        )


    for tgt in target_eligible:

        if indeg.get(
            tgt,
            0,
        ) != 1:

            continue


        current_in = incoming.get(
            tgt,
            [],
        )


        assert len(
            current_in
        ) == 1


        old_src = int(
            current_in[
                0
            ]
        )


        dt_old = (
            time_map[
                tgt
            ]
            -
            time_map[
                old_src
            ]
        )


        if dt_old <= 0:

            continue


        predicted_source = (
            phys[
                tgt
            ]
            -
            float(
                dt_old
            )
            *
            future_velocity[
                tgt
            ]
        )


        target_incumbent[
            tgt
        ] = (
            float(
                np.linalg.norm(
                    phys[
                        old_src
                    ]
                    -
                    predicted_source
                )
            )
            /
            float(
                dt_old
            )
        )


    # --------------------------------------------------------
    # Group eligible endpoints by time
    # --------------------------------------------------------

    source_by_t = {}

    target_by_t = {}


    for nid in source_eligible:

        source_by_t.setdefault(
            time_map[
                nid
            ],
            [],
        ).append(
            nid
        )


    for nid in target_eligible:

        target_by_t.setdefault(
            time_map[
                nid
            ],
            [],
        ).append(
            nid
        )


    for t in source_by_t:

        source_by_t[
            t
        ] = sorted(
            source_by_t[
                t
            ]
        )


    for t in target_by_t:

        target_by_t[
            t
        ] = sorted(
            target_by_t[
                t
            ]
        )


    # --------------------------------------------------------
    # Proposal generation
    # --------------------------------------------------------

    proposal_rows = []

    raw_count = 0

    retained_count = 0


    for gap_size in range(
        MIN_GAP_SIZE,
        MAX_GAP_SIZE + 1,
    ):

        delta_t = (
            gap_size
            +
            1
        )


        for source_t in sorted(
            source_by_t
        ):

            target_t = (
                source_t
                +
                delta_t
            )


            if target_t not in target_by_t:

                continue


            source_ids = source_by_t[
                source_t
            ]


            target_ids = target_by_t[
                target_t
            ]


            if (
                len(
                    source_ids
                ) == 0
                or
                len(
                    target_ids
                ) == 0
            ):

                continue


            source_pos = np.vstack(
                [
                    phys[
                        nid
                    ]

                    for nid
                    in source_ids
                ]
            )


            target_pos = np.vstack(
                [
                    phys[
                        nid
                    ]

                    for nid
                    in target_ids
                ]
            )


            source_vel = np.vstack(
                [
                    past_velocity[
                        nid
                    ]

                    for nid
                    in source_ids
                ]
            )


            target_vel = np.vstack(
                [
                    future_velocity[
                        nid
                    ]

                    for nid
                    in target_ids
                ]
            )


            # ------------------------------------------------
            # K16 forward CV
            # ------------------------------------------------

            source_pred = (
                source_pos
                +
                float(
                    delta_t
                )
                *
                source_vel
            )


            (
                source_dist,
                source_idx,
            ) = query_knn(
                source_pred,
                target_pos,
                QUERY_K,
            )


            source_map = make_rank_map(
                source_ids,
                target_ids,
                source_dist,
                source_idx,
                reverse_pair=False,
            )


            # ------------------------------------------------
            # K16 backward CV
            # ------------------------------------------------

            target_pred = (
                target_pos
                -
                float(
                    delta_t
                )
                *
                target_vel
            )


            (
                target_dist,
                target_idx,
            ) = query_knn(
                target_pred,
                source_pos,
                QUERY_K,
            )


            target_map = make_rank_map(
                target_ids,
                source_ids,
                target_dist,
                target_idx,
                reverse_pair=True,
            )


            # ------------------------------------------------
            # Local best residuals
            # ------------------------------------------------

            source_best = {
                int(
                    source_ids[
                        i
                    ]
                ):
                    float(
                        source_dist[
                            i,
                            0
                        ]
                    )

                for i
                in range(
                    len(
                        source_ids
                    )
                )
            }


            target_best = {
                int(
                    target_ids[
                        i
                    ]
                ):
                    float(
                        target_dist[
                            i,
                            0
                        ]
                    )

                for i
                in range(
                    len(
                        target_ids
                    )
                )
            }


            reciprocal_pairs = (
                set(
                    source_map
                )
                &
                set(
                    target_map
                )
            )


            for (
                src,
                tgt,
            ) in sorted(
                reciprocal_pairs
            ):

                if (
                    src,
                    tgt,
                ) in edge_set:

                    continue


                (
                    source_rank,
                    source_residual,
                ) = source_map[
                    (
                        src,
                        tgt,
                    )
                ]


                (
                    target_rank,
                    target_residual,
                ) = target_map[
                    (
                        src,
                        tgt,
                    )
                ]


                if not asym_3x8(
                    source_rank,
                    target_rank,
                ):

                    continue


                # ASYM3x8 raw cardinality.
                raw_count += 1


                source_degree = int(
                    outdeg.get(
                        src,
                        0,
                    )
                )


                target_degree = int(
                    indeg.get(
                        tgt,
                        0,
                    )
                )


                assert source_degree <= 1
                assert target_degree <= 1


                cuts = (
                    int(
                        source_degree
                        ==
                        1
                    )
                    +
                    int(
                        target_degree
                        ==
                        1
                    )
                )


                source_cv_pf = (
                    float(
                        source_residual
                    )
                    /
                    float(
                        delta_t
                    )
                )


                target_cv_pf = (
                    float(
                        target_residual
                    )
                    /
                    float(
                        delta_t
                    )
                )


                # --------------------------------------------
                # Relative incumbent improvements
                # --------------------------------------------

                source_imp = np.nan

                target_imp = np.nan


                if source_degree == 1:

                    incumbent = float(
                        source_incumbent.get(
                            src,
                            np.nan,
                        )
                    )


                    if np.isfinite(
                        incumbent
                    ):

                        source_imp = (
                            incumbent
                            -
                            source_cv_pf
                        )


                if target_degree == 1:

                    incumbent = float(
                        target_incumbent.get(
                            tgt,
                            np.nan,
                        )
                    )


                    if np.isfinite(
                        incumbent
                    ):

                        target_imp = (
                            incumbent
                            -
                            target_cv_pf
                        )


                required = []


                if source_degree == 1:

                    required.append(
                        source_imp
                    )


                if target_degree == 1:

                    required.append(
                        target_imp
                    )


                if cuts == 0:

                    dominance_any = True

                    dominance_all = True


                else:

                    finite_required = [
                        value

                        for value
                        in required

                        if np.isfinite(
                            value
                        )
                    ]


                    if len(
                        finite_required
                    ) != len(
                        required
                    ):

                        dominance_any = False

                        dominance_all = False


                    else:

                        dominance_any = any(
                            value > 0

                            for value
                            in finite_required
                        )


                        dominance_all = all(
                            value > 0

                            for value
                            in finite_required
                        )


                if not dominance_any:

                    continue


                retained_count += 1


                sym_cv = (
                    source_cv_pf
                    +
                    target_cv_pf
                ) / 2.0


                max_cv = max(
                    source_cv_pf,
                    target_cv_pf,
                )


                source_ratio = safe_ratio(
                    source_residual,
                    source_best[
                        src
                    ],
                )


                target_ratio = safe_ratio(
                    target_residual,
                    target_best[
                        tgt
                    ],
                )


                if (
                    np.isfinite(
                        source_ratio
                    )
                    and
                    np.isfinite(
                        target_ratio
                    )
                ):

                    gmean_ratio = float(
                        np.sqrt(
                            source_ratio
                            *
                            target_ratio
                        )
                    )


                else:

                    gmean_ratio = np.inf


                proposal_rows.append(
                    {
                        "source_id":
                            int(
                                src
                            ),

                        "target_id":
                            int(
                                tgt
                            ),

                        "gap_size":
                            int(
                                gap_size
                            ),

                        "cuts":
                            int(
                                cuts
                            ),

                        "SYM_CV":
                            float(
                                sym_cv
                            ),

                        "MAX_CV":
                            float(
                                max_cv
                            ),

                        "GMEAN_RATIO":
                            float(
                                gmean_ratio
                            ),

                        # Exact precomputed quantities retained
                        # for later scoring features.
                        "__source_cv_pf":
                            float(
                                source_cv_pf
                            ),

                        "__target_cv_pf":
                            float(
                                target_cv_pf
                            ),

                        "__source_incumbent":
                            float(
                                source_incumbent.get(
                                    src,
                                    np.nan,
                                )
                            ),

                        "__target_incumbent":
                            float(
                                target_incumbent.get(
                                    tgt,
                                    np.nan,
                                )
                            ),

                        "__source_improvement":
                            float(
                                source_imp
                            ),

                        "__target_improvement":
                            float(
                                target_imp
                            ),

                        "__dominance_all":
                            bool(
                                dominance_all
                            ),
                    }
                )


            del source_pos
            del target_pos

            del source_vel
            del target_vel

            del source_pred
            del target_pred

            del source_dist
            del source_idx

            del target_dist
            del target_idx

            del source_map
            del target_map

            del source_best
            del target_best

            del reciprocal_pairs


    proposals = pd.DataFrame.from_records(
        proposal_rows
    )


    assert len(
        proposals
    ) == retained_count


    assert not proposals[
        [
            "source_id",
            "target_id",
        ]
    ].duplicated().any()


    del graph
    del nodes
    del edges

    del edge_set
    del incoming
    del outgoing

    del indeg
    del outdeg

    del phys
    del time_map

    del node_ids
    del past_velocity
    del future_velocity

    del source_eligible
    del target_eligible

    del source_incumbent
    del target_incumbent

    del source_by_t
    del target_by_t

    del proposal_rows

    gc.collect()


    return (
        proposals,
        int(
            raw_count
        ),
        int(
            retained_count
        ),
    )


def add_endpoint_ranks(
    proposals,
):

    proposals = proposals.copy()


    for score in RANK_SCORES:

        source_order = (
            proposals[
                [
                    "source_id",
                    "target_id",
                    "gap_size",
                    score,
                ]
            ]
            .sort_values(
                [
                    "source_id",
                    score,
                    "gap_size",
                    "target_id",
                ],
                kind="stable",
            )
        )


        source_order[
            f"{score}_SOURCE_RANK"
        ] = (
            source_order.groupby(
                "source_id",
                sort=False,
            )
            .cumcount()
            +
            1
        )


        proposals[
            f"{score}_SOURCE_RANK"
        ] = (
            source_order[
                f"{score}_SOURCE_RANK"
            ]
            .reindex(
                proposals.index
            )
            .astype(
                np.int32
            )
        )


        target_order = (
            proposals[
                [
                    "source_id",
                    "target_id",
                    "gap_size",
                    score,
                ]
            ]
            .sort_values(
                [
                    "target_id",
                    score,
                    "gap_size",
                    "source_id",
                ],
                kind="stable",
            )
        )


        target_order[
            f"{score}_TARGET_RANK"
        ] = (
            target_order.groupby(
                "target_id",
                sort=False,
            )
            .cumcount()
            +
            1
        )


        proposals[
            f"{score}_TARGET_RANK"
        ] = (
            target_order[
                f"{score}_TARGET_RANK"
            ]
            .reindex(
                proposals.index
            )
            .astype(
                np.int32
            )
        )


        del source_order
        del target_order


    return proposals


def add_shortlist_rank_fields(
    proposals,
):

    p = proposals.copy()


    p[
        "GM_SOURCE_RANK"
    ] = p[
        "GMEAN_RATIO_SOURCE_RANK"
    ].astype(
        np.int32
    )


    p[
        "GM_TARGET_RANK"
    ] = p[
        "GMEAN_RATIO_TARGET_RANK"
    ].astype(
        np.int32
    )


    p[
        "GM_BEST_RANK"
    ] = np.minimum(
        p[
            "GM_SOURCE_RANK"
        ],
        p[
            "GM_TARGET_RANK"
        ],
    ).astype(
        np.int32
    )


    p[
        "GM_MAX_RANK"
    ] = np.maximum(
        p[
            "GM_SOURCE_RANK"
        ],
        p[
            "GM_TARGET_RANK"
        ],
    ).astype(
        np.int32
    )


    p[
        "SYM_BEST_RANK"
    ] = np.minimum(
        p[
            "SYM_CV_SOURCE_RANK"
        ],
        p[
            "SYM_CV_TARGET_RANK"
        ],
    ).astype(
        np.int32
    )


    p[
        "MAX_BEST_RANK"
    ] = np.minimum(
        p[
            "MAX_CV_SOURCE_RANK"
        ],
        p[
            "MAX_CV_TARGET_RANK"
        ],
    ).astype(
        np.int32
    )


    return p


def frozen_shortlist_mask(
    proposals,
):

    return (
        proposals[
            "GM_BEST_RANK"
        ].le(
            8
        )
        |
        (
            proposals[
                "cuts"
            ].le(
                1
            )
            &
            proposals[
                "GM_BEST_RANK"
            ].le(
                20
            )
        )
    )


def attach_scoring_features(
    proposals,
):

    p = proposals.copy()


    # --------------------------------------------------------
    # Temporal
    # --------------------------------------------------------

    p[
        "delta_t"
    ] = (
        p[
            "gap_size"
        ].astype(
            np.int16
        )
        +
        1
    )


    # --------------------------------------------------------
    # Topology
    # --------------------------------------------------------

    p[
        "source_occupied"
    ] = (
        p[
            "__source_incumbent"
        ].notna()
    ).astype(
        np.int8
    )


    p[
        "target_occupied"
    ] = (
        p[
            "__target_incumbent"
        ].notna()
    ).astype(
        np.int8
    )


    reconstructed_cuts = (
        p[
            "source_occupied"
        ]
        +
        p[
            "target_occupied"
        ]
    ).astype(
        np.int8
    )


    assert np.array_equal(
        reconstructed_cuts.to_numpy(),

        p[
            "cuts"
        ].to_numpy(
            dtype=np.int8
        ),
    )


    # --------------------------------------------------------
    # Candidate CV
    # --------------------------------------------------------

    p[
        "source_cv_pf"
    ] = p[
        "__source_cv_pf"
    ].astype(
        float
    )


    p[
        "target_cv_pf"
    ] = p[
        "__target_cv_pf"
    ].astype(
        float
    )


    p[
        "MIN_CV"
    ] = np.minimum(
        p[
            "source_cv_pf"
        ],
        p[
            "target_cv_pf"
        ],
    )


    # --------------------------------------------------------
    # Incumbent-relative
    # --------------------------------------------------------

    p[
        "source_incumbent_cv_pf"
    ] = p[
        "__source_incumbent"
    ].astype(
        float
    )


    p[
        "target_incumbent_cv_pf"
    ] = p[
        "__target_incumbent"
    ].astype(
        float
    )


    p[
        "source_relative_improvement"
    ] = p[
        "__source_improvement"
    ].astype(
        float
    )


    p[
        "target_relative_improvement"
    ] = p[
        "__target_improvement"
    ].astype(
        float
    )


    p[
        "dominance_all"
    ] = p[
        "__dominance_all"
    ].astype(
        np.int8
    )


    # --------------------------------------------------------
    # Required improvement summaries
    # --------------------------------------------------------

    source_occ = p[
        "source_occupied"
    ].astype(
        bool
    ).to_numpy()


    target_occ = p[
        "target_occupied"
    ].astype(
        bool
    ).to_numpy()


    source_imp = p[
        "source_relative_improvement"
    ].to_numpy(
        dtype=float
    )


    target_imp = p[
        "target_relative_improvement"
    ].to_numpy(
        dtype=float
    )


    max_required = np.full(
        len(
            p
        ),
        np.nan,
    )


    min_required = np.full(
        len(
            p
        ),
        np.nan,
    )


    mean_required = np.full(
        len(
            p
        ),
        np.nan,
    )


    mask = (
        source_occ
        &
        ~target_occ
    )


    max_required[
        mask
    ] = source_imp[
        mask
    ]

    min_required[
        mask
    ] = source_imp[
        mask
    ]

    mean_required[
        mask
    ] = source_imp[
        mask
    ]


    mask = (
        ~source_occ
        &
        target_occ
    )


    max_required[
        mask
    ] = target_imp[
        mask
    ]

    min_required[
        mask
    ] = target_imp[
        mask
    ]

    mean_required[
        mask
    ] = target_imp[
        mask
    ]


    mask = (
        source_occ
        &
        target_occ
    )


    max_required[
        mask
    ] = np.maximum(
        source_imp[
            mask
        ],
        target_imp[
            mask
        ],
    )


    min_required[
        mask
    ] = np.minimum(
        source_imp[
            mask
        ],
        target_imp[
            mask
        ],
    )


    mean_required[
        mask
    ] = (
        source_imp[
            mask
        ]
        +
        target_imp[
            mask
        ]
    ) / 2.0


    p[
        "max_required_improvement"
    ] = max_required


    p[
        "min_required_improvement"
    ] = min_required


    p[
        "mean_required_improvement"
    ] = mean_required


    # --------------------------------------------------------
    # Competition counts within frozen shortlist
    # --------------------------------------------------------

    source_count = (
        p.groupby(
            "source_id",
            sort=False,
        )[
            "source_id"
        ]
        .transform(
            "size"
        )
        .astype(
            np.int32
        )
    )


    target_count = (
        p.groupby(
            "target_id",
            sort=False,
        )[
            "target_id"
        ]
        .transform(
            "size"
        )
        .astype(
            np.int32
        )
    )


    p[
        "SOURCE_COMPETITION_COUNT"
    ] = source_count


    p[
        "TARGET_COMPETITION_COUNT"
    ] = target_count


    # --------------------------------------------------------
    # Rank combinations
    # --------------------------------------------------------

    p[
        "GM_RANK_SUM"
    ] = (
        p[
            "GM_SOURCE_RANK"
        ].astype(
            float
        )
        +
        p[
            "GM_TARGET_RANK"
        ].astype(
            float
        )
    )


    p[
        "GM_RANK_LOG_ASYMMETRY"
    ] = np.abs(
        np.log1p(
            p[
                "GM_SOURCE_RANK"
            ].astype(
                float
            )
        )
        -
        np.log1p(
            p[
                "GM_TARGET_RANK"
            ].astype(
                float
            )
        )
    )


    p[
        "GM_SOURCE_RANK_FRAC"
    ] = (
        p[
            "GM_SOURCE_RANK"
        ].astype(
            float
        )
        /
        p[
            "SOURCE_COMPETITION_COUNT"
        ].astype(
            float
        )
    )


    p[
        "GM_TARGET_RANK_FRAC"
    ] = (
        p[
            "GM_TARGET_RANK"
        ].astype(
            float
        )
        /
        p[
            "TARGET_COMPETITION_COUNT"
        ].astype(
            float
        )
    )


    p[
        "GM_BEST_RANK_FRAC"
    ] = np.minimum(
        p[
            "GM_SOURCE_RANK_FRAC"
        ],
        p[
            "GM_TARGET_RANK_FRAC"
        ],
    )


    for col in FEATURE_COLUMNS:

        assert col in p.columns, col


    return p


def endpoint_score_ranks_g3h3(
    frame,
):

    source_order = (
        frame[
            [
                "source_id",
                "target_id",
                "gap_size",
                "GMEAN_RATIO",
                "model_score",
            ]
        ]
        .sort_values(
            [
                "source_id",
                "model_score",
                "GMEAN_RATIO",
                "gap_size",
                "target_id",
            ],
            ascending=[
                True,
                False,
                True,
                True,
                True,
            ],
            kind="stable",
        )
    )


    source_order[
        "source_score_rank"
    ] = (
        source_order.groupby(
            "source_id",
            sort=False,
        )
        .cumcount()
        +
        1
    )


    target_order = (
        frame[
            [
                "source_id",
                "target_id",
                "gap_size",
                "GMEAN_RATIO",
                "model_score",
            ]
        ]
        .sort_values(
            [
                "target_id",
                "model_score",
                "GMEAN_RATIO",
                "gap_size",
                "source_id",
            ],
            ascending=[
                True,
                False,
                True,
                True,
                True,
            ],
            kind="stable",
        )
    )


    target_order[
        "target_score_rank"
    ] = (
        target_order.groupby(
            "target_id",
            sort=False,
        )
        .cumcount()
        +
        1
    )


    result = pd.DataFrame(
        index=frame.index
    )


    result[
        "source_score_rank"
    ] = (
        source_order[
            "source_score_rank"
        ]
        .reindex(
            frame.index
        )
        .astype(
            np.int32
        )
    )


    result[
        "target_score_rank"
    ] = (
        target_order[
            "target_score_rank"
        ]
        .reindex(
            frame.index
        )
        .astype(
            np.int32
        )
    )


    del source_order
    del target_order


    return result


def policy_mask_g3h3(
    frame,
    a,
    b,
):

    sr = frame[
        "source_score_rank"
    ]


    tr = frame[
        "target_score_rank"
    ]


    return (
        (
            sr.le(
                a
            )
            &
            tr.le(
                b
            )
        )
        |
        (
            tr.le(
                a
            )
            &
            sr.le(
                b
            )
        )
    )


def resolve_conflicts_g3h3(
    frame,
):

    if len(
        frame
    ) == 0:

        return frame.copy()


    ordered = (
        frame
        .sort_values(
            [
                "model_score",
                "GMEAN_RATIO",
                "gap_size",
                "source_id",
                "target_id",
            ],
            ascending=[
                False,
                True,
                True,
                True,
                True,
            ],
            kind="stable",
        )
    )


    locked_nodes = set()

    accepted_index = []


    for row in ordered.itertuples():

        src = int(
            row.source_id
        )


        tgt = int(
            row.target_id
        )


        if src in locked_nodes:

            continue


        if tgt in locked_nodes:

            continue


        accepted_index.append(
            row.Index
        )


        locked_nodes.add(
            src
        )


        locked_nodes.add(
            tgt
        )


    return (
        frame.loc[
            accepted_index
        ]
        .copy()
    )


# ============================================================
# ARTIFACT INTEGRITY
# ============================================================

def _sha256_file(path):
    h = hashlib.sha256()

    with Path(path).open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)

            if not chunk:
                break

            h.update(chunk)

    return h.hexdigest()


@lru_cache(maxsize=4)
def _load_frozen_runtime(artifact_dir_string):
    artifact_dir = Path(artifact_dir_string)

    schema_path = (
        artifact_dir
        / "stage12_folds14_rewire_scoring_feature_schema_v1_frozen.json"
    )

    model_path = (
        artifact_dir
        / "stage12_folds14_rewire_logreg_scorer_v1_model.joblib"
    )

    prep_path = (
        artifact_dir
        / "stage12_folds14_rewire_logreg_scorer_v1_preprocessor.npz"
    )

    threshold_path = (
        artifact_dir
        / "stage12_rewire_asym1x5_q9990_no_target_cut_v1_deployment_threshold.json"
    )

    policy_path = (
        artifact_dir
        / "stage12_rewire_asym1x5_q9990_no_target_cut_v1_frozen.json"
    )

    for path in [
        schema_path,
        model_path,
        prep_path,
        threshold_path,
        policy_path,
    ]:
        if not path.exists():
            raise FileNotFoundError(path)

    if _sha256_file(model_path) != MODEL_SHA256:
        raise RuntimeError("Frozen scorer model SHA mismatch")

    if _sha256_file(prep_path) != PREPROCESSOR_SHA256:
        raise RuntimeError("Frozen scorer preprocessor SHA mismatch")

    schema = json.loads(
        schema_path.read_text(encoding="utf-8")
    )

    if schema["feature_schema_sha256"] != FEATURE_SCHEMA_SHA256:
        raise RuntimeError("Frozen feature schema SHA mismatch")

    if list(schema["features"]) != FEATURE_COLUMNS:
        raise RuntimeError("Frozen feature-column mismatch")

    threshold_contract = json.loads(
        threshold_path.read_text(encoding="utf-8")
    )

    if float(threshold_contract["threshold"]) != DEPLOYMENT_THRESHOLD:
        raise RuntimeError("Frozen deployment-threshold mismatch")

    policy = json.loads(
        policy_path.read_text(encoding="utf-8")
    )

    if policy["policy_id"] != POLICY_ID:
        raise RuntimeError("Frozen policy ID mismatch")

    if policy["final_policy_sha256"] != POLICY_SHA256:
        raise RuntimeError("Frozen policy SHA mismatch")

    prep = np.load(
        prep_path,
        allow_pickle=False,
    )

    model = joblib.load(
        model_path
    )

    if prep["feature_columns"].tolist() != FEATURE_COLUMNS:
        raise RuntimeError("Preprocessor feature-column mismatch")

    medians = prep["medians"].astype(
        np.float64,
        copy=True,
    )

    means = prep["means"].astype(
        np.float64,
        copy=True,
    )

    stds = prep["stds"].astype(
        np.float64,
        copy=True,
    )

    if model.coef_.shape != (1, 64):
        raise RuntimeError(
            f"Unexpected model shape: {model.coef_.shape}"
        )

    return {
        "model": model,
        "medians": medians,
        "means": means,
        "stds": stds,
    }


def _transform_frozen_full_dev(frame, runtime):
    X = (
        frame[FEATURE_COLUMNS]
        .apply(
            pd.to_numeric,
            errors="coerce",
        )
        .to_numpy(
            dtype=np.float64,
            copy=True,
        )
    )

    X[
        ~np.isfinite(X)
    ] = np.nan

    missing = np.isnan(X)

    filled = np.where(
        missing,
        runtime["medians"][None, :],
        X,
    )

    scaled = (
        filled
        -
        runtime["means"][None, :]
    ) / runtime["stds"][None, :]

    design = np.concatenate(
        [
            scaled,
            missing.astype(np.float64),
        ],
        axis=1,
    )

    if design.shape[1] != 64:
        raise RuntimeError(
            f"Unexpected design width: {design.shape}"
        )

    if not np.isfinite(design).all():
        raise RuntimeError("Nonfinite frozen design matrix")

    return design.astype(
        np.float32,
        copy=False,
    )


def _score_frozen_full_dev(
    frame,
    runtime,
    batch_size=50_000,
):
    scores = np.empty(
        len(frame),
        dtype=np.float64,
    )

    model = runtime["model"]

    for start in range(
        0,
        len(frame),
        batch_size,
    ):
        stop = min(
            start + batch_size,
            len(frame),
        )

        X = _transform_frozen_full_dev(
            frame.iloc[start:stop],
            runtime,
        )

        scores[start:stop] = (
            model.predict_proba(X)[:, 1]
        )

    if not np.isfinite(scores).all():
        raise RuntimeError("Nonfinite frozen model scores")

    return scores


# ============================================================
# CONTROLLED PRE-CURRENT-BEST BUILDER INJECTION
# ============================================================

_MISSING = object()


def _generate_with_exact_pre_rewire_builder(
    dataset,
    pre_rewire_builder,
):
    global build_current_best

    previous = globals().get(
        "build_current_best",
        _MISSING,
    )

    globals()[
        "build_current_best"
    ] = pre_rewire_builder

    try:
        result = generate_dataset_proposals(
            dataset
        )

    finally:
        if previous is _MISSING:
            globals().pop(
                "build_current_best",
                None,
            )
        else:
            globals()[
                "build_current_best"
            ] = previous

    if not isinstance(result, tuple):
        raise RuntimeError(
            "Frozen proposal generator did not return tuple"
        )

    return result


# ============================================================
# FROZEN ACTION GENERATION
# ============================================================

def build_confirmed_rewire_actions(
    dataset,
    *,
    pre_rewire_builder,
    artifact_dir,
):
    result = _generate_with_exact_pre_rewire_builder(
        dataset,
        pre_rewire_builder,
    )

    proposals = result[0]

    proposals = add_endpoint_ranks(
        proposals
    )

    proposals = add_shortlist_rank_fields(
        proposals
    )

    shortlist = (
        proposals[
            frozen_shortlist_mask(
                proposals
            )
        ]
        .copy()
        .reset_index(
            drop=True
        )
    )

    shortlist = attach_scoring_features(
        shortlist
    )

    runtime = _load_frozen_runtime(
        str(
            Path(artifact_dir).resolve()
        )
    )

    shortlist[
        "model_score"
    ] = _score_frozen_full_dev(
        shortlist,
        runtime,
    )

    ranks = endpoint_score_ranks_g3h3(
        shortlist
    )

    shortlist[
        "source_score_rank"
    ] = ranks[
        "source_score_rank"
    ].to_numpy(
        copy=True
    )

    shortlist[
        "target_score_rank"
    ] = ranks[
        "target_score_rank"
    ].to_numpy(
        copy=True
    )

    rank_mask = policy_mask_g3h3(
        shortlist,
        a=1,
        b=5,
    )

    score_gated = shortlist[
        rank_mask
        &
        shortlist[
            "model_score"
        ].ge(
            DEPLOYMENT_THRESHOLD
        )
    ].copy()

    resolved = (
        resolve_conflicts_g3h3(
            score_gated
        )
        .copy()
        .reset_index(
            drop=True
        )
    )

    target_occupied = pd.to_numeric(
        resolved[
            "target_occupied"
        ],
        errors="raise",
    ).astype(
        int
    )

    selected = (
        resolved[
            target_occupied.eq(0)
        ]
        .copy()
        .reset_index(
            drop=True
        )
    )

    if not pd.to_numeric(
        selected[
            "target_occupied"
        ],
        errors="raise",
    ).astype(
        int
    ).eq(
        0
    ).all():
        raise RuntimeError(
            "NO_TARGET_CUT structural contract violated"
        )

    selected[
        "score_threshold"
    ] = DEPLOYMENT_THRESHOLD

    selected[
        "policy_id"
    ] = POLICY_ID

    return selected


# ============================================================
# GRAPH STATE
# ============================================================

def _runtime_graph_state(graph):
    nodes = (
        graph.node_attrs(
            attr_keys=[
                "node_id",
                "t",
                "z",
                "y",
                "x",
            ]
        )
        .to_pandas()
        .set_index(
            "node_id"
        )
    )

    edges = (
        graph.edge_attrs(
            unpack=True
        )
        .to_pandas()
    )

    outdeg = (
        edges.groupby("source_id")
        .size()
        .astype(int)
        .to_dict()
    )

    indeg = (
        edges.groupby("target_id")
        .size()
        .astype(int)
        .to_dict()
    )

    edge_set = set(
        zip(
            edges[
                "source_id"
            ].astype(int),

            edges[
                "target_id"
            ].astype(int),
        )
    )

    return (
        nodes,

        {
            int(k): int(v)
            for k, v
            in outdeg.items()
        },

        {
            int(k): int(v)
            for k, v
            in indeg.items()
        },

        edge_set,
    )


# ============================================================
# EXACT CONFIRMED GRAPH MUTATION
# ============================================================

def apply_confirmed_rewire_policy(
    dataset,
    graph,
    *,
    pre_rewire_builder,
    artifact_dir,
):
    if dataset.startswith("44b6_"):
        return (
            graph,
            {
                "actions": 0,
                "source_incumbent_edges_removed": 0,
                "edges_added": 0,
                "net_edge_delta": 0,
            },
        )

    if not dataset.startswith("6bba_"):
        raise ValueError(
            f"Unsupported dataset prefix: {dataset}"
        )

    actions = build_confirmed_rewire_actions(
        dataset,
        pre_rewire_builder=pre_rewire_builder,
        artifact_dir=artifact_dir,
    )

    (
        nodes,
        outdeg,
        indeg,
        edge_set,
    ) = _runtime_graph_state(
        graph
    )

    edges = (
        graph.edge_attrs(
            unpack=True
        )
        .to_pandas()
        .copy()
    )

    edges["edge_id"] = edges["edge_id"].astype(int)
    edges["source_id"] = edges["source_id"].astype(int)
    edges["target_id"] = edges["target_id"].astype(int)

    outgoing = {}

    for src, sub in edges.groupby(
        "source_id"
    ):
        outgoing[int(src)] = [
            (
                int(row.edge_id),
                int(row.target_id),
            )
            for row
            in sub.itertuples(
                index=False
            )
        ]

    remove_ids = []
    add_rows = []

    for action in actions.itertuples(
        index=False
    ):
        src = int(action.source_id)
        tgt = int(action.target_id)

        if src == tgt:
            raise RuntimeError(
                "Self-edge in frozen action"
            )

        if (src, tgt) in edge_set:
            raise RuntimeError(
                "Frozen candidate already exists"
            )

        src_out = int(
            outdeg.get(
                src,
                0,
            )
        )

        tgt_in = int(
            indeg.get(
                tgt,
                0,
            )
        )

        # Frozen NO_TARGET_CUT.
        if tgt_in != 0:
            raise RuntimeError(
                (
                    "Target occupied under "
                    "NO_TARGET_CUT",
                    dataset,
                    src,
                    tgt,
                    tgt_in,
                )
            )

        if int(
            action.target_occupied
        ) != 0:
            raise RuntimeError(
                "Frozen action target_occupied != 0"
            )

        if src_out > 1:
            raise RuntimeError(
                (
                    "Unexpected source outdegree",
                    dataset,
                    src,
                    src_out,
                )
            )

        if int(
            action.source_occupied
        ) != int(
            src_out == 1
        ):
            raise RuntimeError(
                "source_occupied topology mismatch"
            )

        expected_cuts = int(
            src_out == 1
        )

        if int(
            action.cuts
        ) != expected_cuts:
            raise RuntimeError(
                "Frozen cuts topology mismatch"
            )

        if src_out == 1:
            src_edges = outgoing.get(
                src,
                [],
            )

            if len(src_edges) != 1:
                raise RuntimeError(
                    "Source incumbent cardinality mismatch"
                )

            remove_ids.append(
                int(
                    src_edges[0][0]
                )
            )

        dist = fv9.recovered_edge_dist(
            nodes,
            src,
            tgt,
            fv9.FROZEN_V9_CONFIG,
        )

        add_rows.append(
            (
                src,
                tgt,
                float(dist),
            )
        )

    if len(remove_ids) != len(
        set(remove_ids)
    ):
        raise RuntimeError(
            "Duplicate incumbent edge removals"
        )

    pre_edges = int(
        graph.num_edges()
    )

    if remove_ids:
        graph.bulk_remove_edges(
            sorted(remove_ids)
        )

    after_remove = int(
        graph.num_edges()
    )

    if (
        pre_edges
        -
        after_remove
    ) != len(remove_ids):
        raise RuntimeError(
            "Edge-removal count mismatch"
        )

    for src, tgt, dist in add_rows:
        if graph.has_edge(
            src,
            tgt,
        ):
            raise RuntimeError(
                "Candidate edge unexpectedly exists"
            )

        graph.add_edge(
            src,
            tgt,
            {
                "edge_dist":
                    float(dist),

                # Frozen evaluation representation contract.
                # Model score is NOT interpreted as calibrated
                # edge probability.
                "edge_prob":
                    1.0,
            },
            validate_keys=True,
        )

    post_edges = int(
        graph.num_edges()
    )

    if post_edges != (
        after_remove
        +
        len(add_rows)
    ):
        raise RuntimeError(
            "Post-mutation edge-count mismatch"
        )

    stats = {
        "actions":
            int(
                len(actions)
            ),

        "source_incumbent_edges_removed":
            int(
                len(remove_ids)
            ),

        "edges_added":
            int(
                len(add_rows)
            ),

        "net_edge_delta":
            int(
                post_edges
                -
                pre_edges
            ),
    }

    return graph, stats
